version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --production
  build:
    commands:
      - npm run build
      - cp -r node_modules dist/
      
artifacts:
  files:
    - dist/**/*
    - template.yaml